name: driver_phone_monitor
description: Ứng dụng cảnh báo khi sử dụng điện thoại lái xe
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^7.0.0
  geolocator: ^14.0.2
  permission_handler: ^10.4.0
  vibration: ^1.7.4
  flutter_local_notifications: ^13.0.0
  audioplayers: ^6.1.0
  background_fetch: ^1.2.3
  connectivity_plus: ^6.0.0
  dio: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/alert.mp3

