name: driver_phone_monitor
description: Monitor phone use while driving - iOS background via Location
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  sensors_plus: ^2.3.0
  flutter_local_notifications: ^12.0.0
  permission_handler: ^10.2.0
  vibration: ^1.7.4

flutter:
  uses-material-design: true